name: Testing

on: push

env:
  VITE_API_URL: ${{ vars.VITE_API_URL}}

jobs:
  test:
    name: Tests passes
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ Git checkout
        uses: actions/checkout@v4

      - name: ðŸ’¾ Install dependencies (retry up to 3 times)
        run: |
          for i in 1 2 3; do
            npm ci && break || sleep 10
          done

      - name: ðŸ§ª Testing
        run: npm test
